version: '3'

services:
  db:
    container_name: db
    build:
      context: ./mariadb
    volumes:
      - ./.data/db:/var/lib/mysql
      - ./logs/mariadb:/var/log/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: ${TIMEZONE}
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - default
  
  app:
    container_name: app
    build:
      context: ./php7-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ${APP_PATH}:/var/www/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - default

  web:
    container_name: web
    build:
      context: ./nginx
      args:
        - 'app'
        - '9000'
    volumes:
      - ${APP_PATH}:/var/www/app
      - ./logs/nginx/:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    networks:
      - default

networks:
  default:
    driver: bridge